before_script:
 - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
 - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
 - brew update
 - brew install -y heroku-toolbelt
 - gem install dpl

staging:
 stage: deploy
 variables:
  HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
 script:
 - dpl --provider=heroku --app=staging-billshandler --api-key=$HEROKU_API_KEY
 - heroku run rake db:migrate --exit-code --app staging-billshandler
 only:
 - master
production:
 stage: deploy
 variables:
  HEROKU_API_KEY: $HEROKU_PRODUCTION_API_KEY
 script:
 - dpl --provider=heroku --app=production-billshandler --api-key=$HEROKU_API_KEY
 - heroku run rake db:migrate --exit-code --app production-billshandler
 only:
 - production
