# Generated by Django 2.1.3 on 2019-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20190113_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Uploaded image'),
        ),
    ]
