# Generated by Django 2.1.3 on 2019-01-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20190113_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bills/images/'),
        ),
    ]
