# Generated by Django 2.1.3 on 2019-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_bill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
