# Generated by Django 2.1.3 on 2019-02-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20190219_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billDate',
            field=models.DateTimeField(default='1999-01-01T00:00:00.000000Z'),
        ),
    ]
